# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            # enabled: false
            token_id: submit  
            field_name: 'amichiamoci_csrf_token'

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
    #csrf_protection: false
