# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    #esi: true
    #fragments: true
    default_locale: it
    
    #trusted_proxies: 'private_ranges'
    trusted_proxies: '127.0.0.1,172.20.0.2,10.89.0.5,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
