hwi_oauth:

    firewall_names: [main]
    
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%env(FB_ID)%'
            client_secret:       '%env(FB_SECRET)%'
            scope:               "email public_profile"

        google:
            type:                google
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               "email profile"
            options:
                access_type:     offline

        microsoft:
            type:          azure
            client_id:     '%env(AZURE_ID)%'
            client_secret: '%env(AZURE_SECRET)%'
            options:
                application: common
        
        github:
            type:                github
            client_id:           '%env(GITHUB_ID)%'
            client_secret:       '%env(GITHUB_SECRET)%'
            scope:               'read:user'
    connect:
        account_connector: App\Security\OAuthConnector
