
pwa:
  manifest:
    enabled: true

    name: "Amichiamoci App"
    description: "App di Amichiamoci per rimanere aggiornati sulla Manifestazione"
    short_name: "Amichiamoci"
    
    start_url: '%env(BASE_PATH)%/public/'
    scope: '$env(BASE_PATH)%/public/'
    display: "standalone"
    background_color: "#ffffff"

    dir: "ltr"
    lang: "it"
    orientation: "portrait"

    icons:
      - src: "./images/favicon.png"
        sizes: [256]

    
    shortcuts:
      - name: "Vedi la classifica"
        short_name: "Classifica"
        description: "Apri l'app direttamente sulla classifica."
        url: "./leaderboard"

      - name: "Partite del giorno"
        short_name: "Partite"
        description: "Apri l'app direttamente sulle partite."
        url: "./matches"