
pwa:
  manifest:
    enabled: true

    name: "Amichiamoci App"
    description: "App di Amichiamoci per rimanere aggiornati sulla Manifestazione"
    short_name: "Amichiamoci"
    
    start_url: './'
    scope: '%env(APP_PATH)%'
    display: "standalone"
    background_color: "#ffffff"

    dir: "ltr"
    lang: "it"
    orientation: "portrait"

    icons:
      - src: "./images/favicon.png"
        sizes: [256]

    
    shortcuts:
      - name: "Vedi la classifica"
        short_name: "Classifica"
        description: "Apri l'app direttamente sulla classifica."
        url: "./leaderboard"

      - name: "Partite di pallavolo"
        short_name: "Pallavolo"
        description: "Apri l'app direttamente sulle partite di pallavolo."
        url: "./matches/pallavolo"
      
      - name: "Partite di calcio"
        short_name: "Calcio"
        description: "Apri l'app direttamente sulle partite di calcio."
        url: "./matches/calcio"

      - name: "Partite di basket"
        short_name: "Basket"
        description: "Apri l'app direttamente sulle partite di basket."
        url: "./matches/basket"

      - name: "Profilo"
        short_name: "Profilo"
        description: "Il mio profilo."
        url: "./profile"