pwa:
  image_processor: pwa.image_processor.gd

  #favicons:
  #  enabled: true
  #  src: assets/logos/favicon.png

  manifest:
    enabled: true

    name: "Amichiamoci App"
    description: "App di Amichiamoci per rimanere aggiornati sulla Manifestazione"
    short_name: "Amichiamoci"
    categories: ['event', 'fundraising', 'sports']
    
    scope: "/"
    start_url: "./"
    display: "standalone"
    background_color: "#ffffff"

    dir: "ltr"
    lang: "it"
    orientation: "portrait"

    icons:
      - src: "logos/favicon.png"
        sizes: [256]

    #serviceworker:
    #  enabled: true
    #  src: "sw.js"
    #  workbox:
    #    asset_cache:
    #      enabled: true

    shortcuts:
      - name: "Vedi la classifica"
        short_name: "Classifica"
        description: "Apri l'app direttamente sulla classifica."
        url: leaderboard
        #icons:
        #  - src: "icons/feature2-96x96.png"
        #    sizes: [96]

      - name: "Partite di pallavolo"
        short_name: "Pallavolo"
        description: "Apri l'app direttamente sulle partite di pallavolo."
        url:
          path: matches
          params:
            sport: pallavolo
      
      - name: "Partite di calcio"
        short_name: "Calcio"
        description: "Apri l'app direttamente sulle partite di calcio."
        url:
          path: matches
          params:
            sport: calcio

      - name: "Partite di basket"
        short_name: "Basket"
        description: "Apri l'app direttamente sulle partite di basket."
        url:
          path: matches
          params:
            sport: basket

      - name: "Profilo"
        short_name: "Profilo"
        description: "Il mio profilo."
        url: profile