services:
  app:
    build:
      context: .
    restart: always
    env_file: ./.env.local
    volumes:
      - ./var/log:/app/var/log:rw
      - ./var/data:/app/var/data:rw
    ports:
      - 8080:8080
    container_name: app