name: amichiamoci

services:
  app:
    build:
      context: ../
      args:
        APP_ENV: ${APP_ENV:-prod}
    profiles: [dev, prod, test]
    restart: always
    container_name: app
    env_file: ../.env.local
    environment:
      REDIS_DSN: redis://redis:6379
    volumes:
      - ../var/log:/app/var/log:rw
      - ../var/data:/app/var/data:rw
      - php_sessions:/app/var/sessions:rw
    ports:
      - 8080:8080
    networks:
      - amichiamoci_network
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - amichiamoci_network

volumes:
  php_sessions:

networks:
  amichiamoci_network:
    driver: bridge