name: amichiamoci

services:
  app:
    build:
      context: ../
      args:
        APP_ENV: ${APP_ENV:-prod}
    profiles: [dev, prod, test]
    restart: always
    container_name: app
    env_file: ../.env.local
    volumes:
      - ../var/log:/app/var/log:rw
      - ../var/data:/app/var/data:rw
    ports:
      - 8080:8080
      - 9003:9003
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 5s
      timeout: 3s
      retries: 5
