services:
  amichiamoci-app:
    image: ghcr.io/amichiamoci/app:latest
    restart: always
    environment:
      DATABASE_URL: mysql://app:${MYSQL_PASSWORD}@mariadb:3306/${MYSQL_DB}?charset=utf8mb4
    ports:
      - 80:80
    networks:
      db:
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: app
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
     - mysql-vol:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      db:   
    depends_on:
      - mariadb 

networks:
  db:
    driver: bridge
volumes:
  mysql-vol:
    driver: azure_file
    driver_opts:
      share_name: ${VOLUME_SHARE_NAME}
      storage_account_name: ${STORAGE_ACCOUNT}