services:
  app:
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: always
    env_file:  ../.env.local
    volumes:
      - ./uploads:/app/content/uploads:rw
      - ./cache:/app/cache/:rw
      - ./log:/app/var/log
      - ../var/data.db:/app/var/data.db:rw
    ports:
      - 80:80