services:
  app:
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: always
    env_file:  ../.env.local
    volumes:
      - ../var:/app/var:rw
    ports:
      - 80:80
    container_name: app
    networks:
      - reverse-proxy
  #cloudflare:
  #  image: cloudflare/cloudflared
  #  container_name: cloudflared
  #  env_file: ./cloudflare.env
  #  command: tunnel --no-autoupdate run
  #  networks:
  #    - reverse-proxy
  #whoami:
  #  image: traefik/whoami
  #  expose:
  #    - 80:80
  #  container_name: app
  #  networks:
  #    - reverse-proxy

networks:
  reverse-proxy: