services:
  amichiamoci-app:
    image: ghcr.io/amichiamoci/app:latest
    restart: always
    environment:
      DATABASE_URL: mysql://app:supersecretpassword@mariadb:3306/app?charset=utf8mb4
    ports:
      - 80:80
      - 2222:2222
    networks:
      db:
    depends_on:
      - mariadb
    volumes:
     - "${WEBAPP_STORAGE_HOME}/ApacheLogs:/var/www/html/var/log"
     - "${WEBAPP_STORAGE_HOME}/ApacheCache:/var/www/html/var/cache/"

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_ROOT_PASSWORD: supersecretpassword
    expose:
      - "3306"
    volumes:
     - "${WEBAPP_STORAGE_HOME}/db:/var/lib/mysql"
    networks:
      db:

networks:
  db:
    driver: bridge